services:
    app:
        container_name: ydh-sider-obfuscation-service
        build:
            context: .
        deploy:
            resources:
                limits:
                    cpus: ${DOCKER_APP_CPUS:-0}
                    memory: ${DOCKER_APP_MEMORY:-0}
        env_file: .env
        environment:
            LOG_ROTATION_DATE_FORMAT:
            LOG_ROTATION_FILENAME:
            NODE_ENV: production
            SERVICE_HOST: 0.0.0.0
        healthcheck:
            test: curl localhost:${SERVICE_PORT:-8204}/healthcheck
            interval: 60s
            timeout: 3s
            start_period: 5s
            retries: 3
        logging:
            options:
                max-file: ${LOG_ROTATION_MAX_LOGS:-10}
                max-size: ${LOG_ROTATION_MAX_SIZE:-100m}
        ports:
            - 127.0.0.1:${SERVICE_PORT:-8204}:${SERVICE_PORT:-8204}
        restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
