services:
    app:
        container_name: ydh-sider-obfuscation-service
        build:
            context: .
        env_file: .env
        environment:
            LOG_ROTATION_DATE_FORMAT:
            LOG_ROTATION_FILENAME:
            NODE_ENV: production
            SERVICE_HOST: 0.0.0.0
        logging:
            options:
                max-file: ${LOG_ROTATION_MAX_LOGS:-10}
                max-size: ${LOG_ROTATION_MAX_SIZE:-100m}
        ports:
            - 127.0.0.1:${SERVICE_PORT:-8204}:${SERVICE_PORT:-8204}
