name: CD

on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: GoogleCloudPlatform/release-please-action@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  release-type: node
                  package-name: ydh-sider-obfuscation-service
