name: CI

on:
    push:
        paths-ignore:
            - 'docs/**'
            - '*.md'
    pull_request:
        paths-ignore:
            - 'docs/**'
            - '*.md'

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - name: Install
              run: yarn --immutable
            - name: Install
              run: yarn --immutable
            - name: Run ESLint
              run: yarn lint
            - name: Run Prettier
              run: yarn lint:prettier:ci

    build:
        name: Build
        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install
              run: yarn --immutable
            - name: Run Tests
              run: |
                  cp .env.template .env.test
                  yarn dupe-check
                  yarn jest-coverage
            - name: Coveralls Parallel
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel: true

    coverage:
        name: Aggregate Coverage Calculations
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Coveralls Finished
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel-finished: true
